export const ADD_INGEREDIENT = 'ADD_INGEREDIENT';
export const REMOVE_INGEREDIENT = 'REMOVE_INGEREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
